### ISSUE TITLE
Misleading information about ONELOGIN_CUSTOMPATH

### ISSUE THREAD

**Issue by oleg-andreyev** [nbgrp/onelogin-saml-bundle#12]
As of today it's impossible to configure custom path for certs because when this bundle is configuring `\OneLogin\Saml2\Settings` it's already passing `$settings` will all information resolved.

Workaround: use %env()% with cert-content.

**Comment by a-menshchikov** [comment]
@oleg-andreyev Hello.
There is no misleading, but you need to kept in mind the following things.

1. `ONELOGIN_CUSTOMPATH` should be a global constant, not an environment variable:
```
define('ONELOGIN_CUSTOMPATH', '...');  //  do not forget about tail slash, e.g. "/some/path/"
```
Usually it's present in a front controller (`public/index.php`).

2. Certificate and key should be present in PEM format (with `-----BEGIN...` and `-----END...` marks).

3. You can use this ability for the single IdP only (if you have a few one). Other ones should be configured through the bundle configuration.

**Comment by a-menshchikov** [comment]
@oleg-andreyev is my answer above solves this issue?
