### ISSUE TITLE
Deprecation Note in Symfony 6.2

### ISSUE THREAD

**Issue by HerHde** [nbgrp/onelogin-saml-bundle#21]
Using the current Symfony 6.2 release, I get the following deprecation warning:

`The "Nbgrp\OneloginSamlBundle\Onelogin\AuthArgumentResolver" class implements "Symfony\Component\HttpKernel\Controller\ArgumentValueResolverInterface" that is deprecated since Symfony 6.2, implement ValueResolverInterface instead.`

I would appreciate, if you would fix this. Thank you.

**Comment by AbdullahAlhariri** [comment]
I have this deplrication too, I'm using symfony 6.2.5 with php 8.1
I think this deprication should be fixed
