### ISSUE TITLE
new user created at each connection

### ISSUE THREAD

**Issue by likou31** [nbgrp/onelogin-saml-bundle#3]
Hello !
I'm having an issue where each time I log into my application, a new entity is created and I would like to know how can I have just 1 entity user related to the identifier please.

For example, if I log in with the same credentials twice, than I'll have 2 entity of the same user in my database, though I'd like to only have one (that's the point).

If someone can help, thank you a lot in advance !

**Comment by a-menshchikov** [comment]
Hello @likou31 
Could you show your security settings (yaml) and your User class?

**Comment by likou31** [comment]
Actually I found a solution.

It was the provider's fault.

In the SamlUserProvider in loadUserByIdentifier(), it creates a new userClass everytime.
I created my own UserProvider that extends the SamlUserProvider, and I changed the method like this (I also changed the __construct method to add the repository) : 

```
public function __construct(
        protected string $userClass,
        protected array $defaultRoles,
        protected UserRepository $repository,
        ManagerRegistry $doctrine
    ) {
        $this->repository = $doctrine->getManager()->getRepository('App:User');
        if (!is_a($userClass, UserInterface::class, true)) {
            throw new \InvalidArgumentException('The $userClass argument should be a class implementing the '.UserInterface::class.' interface.');
        }
    }

    public function loadUserByIdentifier(string $identifier): UserInterface
    {
        $user = $this->repository->loadUserByIdentifier($identifier);
        if ($user != null) {
            return $user;
        } else {
            return new $this->userClass($identifier, $this->defaultRoles);
        }
    }
```

If it can help anyone, I'll be happy !

**Comment by a-menshchikov** [comment]
> In the SamlUserProvider in loadUserByIdentifier(), it creates a new userClass everytime.

It's exactly what it created for. If you want to load a user from database, the [Entity User Provider](https://symfony.com/doc/current/security/user_providers.html#entity-user-provider) might be suitable for you.

Also, I recommend you to read [Just-in-time user provisioning](https://github.com/nbgrp/onelogin-saml-bundle#just-in-time-user-provisioning) section from README.

**Comment by likou31** [comment]
For my needs, I need to load it from the saml server, and persist the user. But not create each time a new user entity. (and I need to do the relation between others entities for example)

**Comment by a-menshchikov** [comment]
IIUC Just-in-time user provisioning is what you need. Use of the Saml User Factory is more convenient approach than the custom user provider which instantiates new User. But if it works for you and looks clearer, it's also good. =)
