### ISSUE TITLE
Multiple idP: restrict email by format

### ISSUE THREAD

**Issue by dcr31000** [nbgrp/onelogin-saml-bundle#35]
Hi,

I'm using nbgrp/onelogin-saml-bundle with multiple idP.
Users are mapped and logged by email.

I would like to restrict sign in and login only for email like "@company-idp-name.com".

Could you please help me to do this ?

Thanks

**Comment by a-menshchikov** [comment]
@dcr31000 hi.
You can look for [User Checkers](https://symfony.com/doc/current/security/user_checkers.html) e.g. The `checkPreAuth` method will be called after handling of SamlResponse and before user authentication, so you could check the user email and throw an appropriate exception if it needed (see [available exceptions](https://github.com/symfony/symfony/tree/6.2/src/Symfony/Component/Security/Core/Exception)).

**Comment by dcr31000** [comment]
@a-menshchikov seems to be what I need, thanks

Do you know how I can see from wich idp the user is from ?
For example, I would like to authorize emails as "@idp1.com" for idp1 and "@idp2.com" for idp2 etc.

**Comment by a-menshchikov** [comment]
I can only suggest you to pass something helpful in the SAML response attributes. There is no way to pass the IdP name to the user properties.

**Comment by a-menshchikov** [comment]
@dcr31000 you can also use [`Nbgrp\OneloginSamlBundle\Idp\IdpResolverInterface::resolve`](https://github.com/a-menshchikov/onelogin-saml-bundle/blob/8fe8e7f6b656cfb2d02b20996649531c96c88970/src/Idp/IdpResolverInterface.php) which resolve the IdP name from incoming request.
