### ISSUE TITLE
Routes not working after fresh installation

### ISSUE THREAD

**Issue by DigitalTimK** [nbgrp/onelogin-saml-bundle#39]
## Background
After upgrading from Symfony 5.4 to Symfony 6.3, I had to change from `hslavich/oneloginsaml-bundle` to `nbgrp/onelogin-saml-bundle` too. Once removed `hslavich/oneloginsaml-bundle`, I did a fresh installation of `nbgrp/onelogin-saml-bundle`.

## Problem
The routes (like `saml_login` and `saml_acs`) coudn't be found.

## Solution
I added this manually into `/config/routes.yaml`:
```
nbgrp_onelogin_saml:
    resource: "@NbgrpOneloginSamlBundle/Resources/config/routes.php"
```

## Proposal:
I don't know if this is a bug, but it would be helpful to know, if it should be working like this. If yes, it would be beneficial to have this in your `README.md`-file. (and/or to fix the bug)

**Comment by a-menshchikov** [comment]
Hi @DigitalTimK 
You're right, but it's already discribed in the README (just before the [Multiple IdP](https://github.com/nbgrp/onelogin-saml-bundle#multiple-idp) section).

**Comment by DigitalTimK** [comment]
Oh... haven't seen this. Strange. But thanks!
