### ISSUE TITLE
Symfony 7 support?

### ISSUE THREAD

**Issue by back-2-95** [nbgrp/onelogin-saml-bundle#44]
As this is mentioned to be for Symfony 6 and newer?

Maybe create just pre-release where composer constraints are updated so people can test themselves if this works?

**Comment by a-menshchikov** [comment]
Hi @back-2-95 
I have plans for add Symfony 7 support in the comming weeks.

**Comment by back-2-95** [comment]
Thank you!

**Comment by a-menshchikov** [comment]
@back-2-95 you can test Symfony 7.0 support with [branch 2.0](https://github.com/nbgrp/onelogin-saml-bundle/tree/2.0). I'm coming to release it simultaneously with the Symfony.

**Comment by back-2-95** [comment]
Thanks @a-menshchikov. I'll try to put it to test.

**Comment by back-2-95** [comment]
Ok, I tested with 2.0 branch and Google SSO. Login works, I have still something with logout, prolly something with configuration.

**Comment by back-2-95** [comment]
My logout problems are related to this https://github.com/SAML-Toolkits/php-saml/issues/299
so I guess not anyway related to Symfony 7 or this branch.

**Comment by back-2-95** [comment]
Hi @a-menshchikov ! Symfony 7.0.0 was released 🎉

**Comment by a-menshchikov** [comment]
Hi @back-2-95 
And we have done too. :slightly_smiling_face:
