### ISSUE TITLE
Inject <saml:Subject><saml:NameID> into User-Entity

### ISSUE THREAD

**Issue by FranzBruckner** [nbgrp/onelogin-saml-bundle#5]
I'm using Wordpress as IDP.
The free version of the WP-Plugin (https://de.wordpress.org/plugins/miniorange-wp-as-saml-idp/) **does not set any attributes.
The only property which is set in the response is <NameID> in <saml:Subject>**

![Bildschirmfoto-2022-02-10-um-21 55 04](https://user-images.githubusercontent.com/3646708/153499108-2bb05a9f-58bd-482f-a22b-a04e3e4c8eb4.png)

This value exists in OneLogin\Saml2\Auth $nameId, SamlAuthenticator can access this property.
But i don't see a way to inject that property into the UserEntity.

SamlAuthenticator cannot be replaced via DI, there is no Event. 
**Am I missing something? Is there a little hack?**

By the way...
As i can see Nbgrp\OneloginSamlBundle\Security\Http\Authenticator\SamlAuthenticator::extractIdentifier() would return exact this value, if identifier_attribute is not set in options.

https://github.com/nbgrp/onelogin-saml-bundle/blob/cdf08b8c1338453b98f616c66094c52ca4141f0a/src/Security/Http/Authenticator/SamlAuthenticator.php#L184

Problem: As i can see, it's not possible to delete "identifier_attribute" from $this->options via yaml. It's not possible to delete / unset keys with yaml.

**Comment by a-menshchikov** [comment]
@FranzBruckner thank you! I will fix this ASAP.

**Comment by a-menshchikov** [comment]
@FranzBruckner I will be grateful if you can test 1.0 branch and let me know if there is no problem anymore.

**Comment by FranzBruckner** [comment]
Hi,
thanks for the quick response. I think your fix has resolved that.

**1.) Unfortunately I'm getting an error when using dev-branch:**
![image](https://user-images.githubusercontent.com/3646708/153564705-0c748046-dfe2-43ff-8484-9fb570349191.png)

As i can see, SamlAuthenticationSuccessHandler extends DefaultAuthenticationSuccessHandler which needs at least one argument (Symfony 6): 
public function __construct(HttpUtils $httpUtils, array $options = [])
I have tried to figure out how to resolve that issue, but my knowledge on that is not enough.

**Comment by a-menshchikov** [comment]
@FranzBruckner yeah, I'm working on it right now. =)

**Comment by a-menshchikov** [comment]
@FranzBruckner Check it one more time, please.

**Comment by a-menshchikov** [comment]
Try v1.0.4. If you'll see any problem — let me know.
Thank you again for your participation.
