### ISSUE TITLE
Upgrade to Symfony 7.0 and 7.1

### ISSUE THREAD

**Issue by neothone** [nbgrp/onelogin-saml-bundle#56]
Hello

Can you update the composer.json file for compatibility with symfony/config 7+ ?

Today when we try to upgrade Symfony 6.4 to Symfony 7.0 we have this error : 
 - nbgrp/onelogin-saml-bundle[v1.2.0, ..., v1.3.2] require symfony/config ^6 -> found symfony/config[v6.0.0, ..., v6.4.8] but these were not loaded, likely because it conflicts with another require.
    - nbgrp/onelogin-saml-bundle v1.4.0 requires symfony/config ^6.4 -> found symfony/config[v6.4.0, ..., v6.4.8] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires nbgrp/onelogin-saml-bundle ^1.2 -> satisfiable by nbgrp/onelogin-saml-bundle[v1.2.0, ..., v1.4.0].

Thank you

**Comment by a-menshchikov** [comment]
Hi @mathieu-dumoutier 
You should use nbgrp/onelogin-saml-bundle **v2** with Symfony 7.x.

**Comment by neothone** [comment]
Thank you :)
